name: Herring Cove
author: Herring Cove
markdown: kramdown
highlighter: rouge
baseurl: /python-quick-reference
description: theme for jekyll
github: https://github.com/SteelyWing/python-quick-reference
# twitter: http://www.twitter.com/
# facebook: http://www.facebook.com
# linkedin: http://www.linkedin.com
# email: rnpatel[at]me.com
# location: 42°2'16"N   70°12'47"W
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.

