# Site settings
title: Python 3
# email: your-email@domain.com
description: "A python quick reference."
baseurl: "/python-quick-reference"
url: "http://steelywing.github.io"

# Build settings
markdown: redcarpet
highlighter: rouge
# permalink: pretty
redcarpet:
  extensions: [with_toc_data, tables]
