# Site settings
title: Python 3 Quick Reference
# email: your-email@domain.com
description: "A python quick reference."
baseurl: "/python-quick-reference"
url: "http://steelywing.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
kramdown:
  use_coderay: true
  coderay:
    coderay_line_numbers: ~
    coderay_css: class
