# Site settings
title: Python 3 Quick Reference
email: steely.wing@gmail.com
description: Python 3 quick reference.
baseurl: "/python-quick-reference"
url: "http://steelywing.github.io"

# Build settings
markdown: redcarpet
# highlighter: ~
highlighter: rouge
# highlighter: pygments
# permalink: pretty
defaults:
  - scope:
      path: ""
    values:
      layout: ~
redcarpet:
  extensions: [with_toc_data, tables]
gems:
  - jekyll-sitemap

collections:
  docs:
    output: false
